---

# Install the perfsonar repos and base OS updates
- name: "{{ ansible_os_family }} Install"
  include: "{{ ansible_os_family }}.yml"
  when: ansible_os_family | default('') != ''

- name: keyserver
  apt_key:
    url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
    state: present

#- name: Disable SELinux
 # selinux:
  #  state: disabled
  #register: sel

- name: https transport 
  apt: 
    name: apt-transport-https
    state: present 

- name: create file
  lineinfile:
    path: /etc/apt/sources.list.d/bintray.rabbitmq.list
    line: deb https://dl.bintray.com/rabbitmq-erlang/debian bionic erlang-22.x
    create: yes

- name: add rabbitmq
  lineinfile:
    path: /etc/apt/sources.list.d/bintray.rabbitmq.list
    line: deb https://dl.bintray.com/rabbitmq/debian bionic main
    create: yes

- name: adding repository
  get_url: 
    url: https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
    dest: /etc

- name: depackage
  dpkg_selections:
    name: erlang-solutions_1.0 
    selection: install

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: reload
  systemd: 
    daemon_reload: yes

- name: install package
  package: 
    name: 
      - erlang-base
      - erlang-asn1 
      - erlang-crypto
      - erlang-eldap
      #- erlang-ftp 
      - erlang-inets 
      - erlang-mnesia
      - erlang-os-mon 
      - erlang-parsetools
      - erlang-public-key 
      - erlang-runtime-tools 
      - erlang-snmp 
      - erlang-ssl
      - erlang-syntax-tools 
      #- erlang-tftp 
      - erlang-tools 
      - erlang-xmerl
      - erlang-nox
    state: present 


#- name: Disable SELinux
 # selinux:
  #  state: disabled
 # register: sel

#- name: open port for rabbitmq
 # ufw:
  #  rule: allow
   # port: "5672"
    #proto: tcp

#- name: reboot
 # reboot:
  #when: sel.changed

#- name: copying rabbitmq repo
 # get_url:
 #   url: https://raw.githubusercontent.com/perfsonar/archiving-sandbox/master/central-archive/files/rabbit.repo
#    dest: /etc/yum.repos.d/rabbit.repo


- name: install package
  ignore_errors: yes  
  package:
    name:
      - python-psutil
      - python-pika
      - python3
      - python3-requests
      - python3-dateutil
      - python3-pycurl
      - socat
      - logrotate
      - init-system-helpers
      - adduser
      - wget
      - rabbitmq-server
    state: present

- name: get package
  get_url: 
    url: https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.8.5/rabbitmq-server_3.8.5-1_all.deb
    dest: /etc

- name: depackage
  dpkg_selections:
    name: rabbitmq-server_3.8.5-1_all.deb
    selection: install

- name: reload daemon
  systemd:
    daemon_reload: yes

- name: open port for rabbitmq
  ufw:
    rule: allow
    port: "5672"
    proto: tcp

#- name: stop firewalld
 # systemd:
  #   name: firewalld
   #  state: stopped
     
- name: start rabbitmq
  systemd:
    enabled: yes
    name: rabbitmq-server
    state: started

- name: enable rabbitmq-management
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled

- name: add in the default rabbitmq user
  rabbitmq_user:
    user: hi 
    password: hi
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
