---
# tasks file for RedHat.yml

# Setup the required repositories
# yum install epel-release
- name: (RedHat) Add EPEL repository
  tags: [ 'elastic::install' ]
  yum:
    name: epel-release
    state: present

# Make sure we have the latest upgrades installed
#- name: (RedHat) Install system updates
#  tags: [ 'elastic::install' ]
#  yum:
#    name: '*'
#    state: latest
#    update_cache: yes
#  ignore_errors: True
#  when: ( elastic_os_update | default('false')) == True
